steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/projectforpoc-489612/gcp-poc-app', '.']

images:
  - 'gcr.io/projectforpoc-489612/gcp-poc-app'

options:
    logging: GCS_ONLY
    logsBucket: 'gs://shamimgcpbucket'
	serviceAccount: 'projects/projectforpoc-489612/serviceAccounts/shamim-service-account@projectforpoc-489612.iam.gserviceaccount.com'

