spring.application.name=GCPStorage
# Using a local file path
#spring.cloud.gcp.credentials.location=file:C:\Users\shamians\eclipse-workspace\JavaProjectTest\GCPStorage.zip_expanded\GCPStorage\src\main\resources\serviceaccountKey.json
#spring.cloud.gcp.credentials.location=classpath:serviceaccountKey.json
server.port=9090
#logging.level.org.springframework.web=DEBUG

# Tell Spring to use the project ID from the environment
spring.cloud.gcp.project-id=projectforpoc-489612
# This enables auto-detection of credentials on GCP
spring.cloud.gcp.storage.enabled=true